# Generated by Django 3.0.2 on 2020-04-20 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PregnancyDiagnosis",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField()),
                ("diagnosis", models.BooleanField()),
                (
                    "sheep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pregnancyDiagnostics",
                        to="core.Sheep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pregnancyDiagnostics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
