# Generated by Django 3.0.5 on 2020-04-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_breed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sheep",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("earringNumber", models.IntegerField(blank=True, null=True, unique=True)),
                ("birthday", models.DateField()),
                ("sex", models.CharField(choices=[("F", "Female"), ("M", "Male")], default="F", max_length=1)),
                ("teethQuantity", models.IntegerField()),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="sheeps", to="core.Breed"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="sheeps", to="core.Category"
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="father_children",
                        to="core.Sheep",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mother_children",
                        to="core.Sheep",
                    ),
                ),
            ],
        ),
    ]
