# Generated by Django 3.0.5 on 2020-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sheep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheep",
            name="earringNumber",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
