# Generated by Django 3.0.5 on 2020-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_group"),
    ]

    operations = [
        migrations.DeleteModel(name="Group",),
    ]
