# Generated by Django 3.0.5 on 2020-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200506_1716"),
    ]

    operations = [
        migrations.AddField(model_name="sheep", name="pregnant", field=models.BooleanField(default=False),),
    ]
