# Generated by Django 3.0.5 on 2020-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_sheep_pregnant"),
    ]

    operations = [
        migrations.AddField(model_name="sheep", name="weight", field=models.FloatField(default=0),),
        migrations.AlterField(model_name="sheep", name="teethQuantity", field=models.IntegerField(default=0),),
    ]
