# Generated by Django 3.0.5 on 2020-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20200513_1715"),
    ]

    operations = [
        migrations.AddField(model_name="sheep", name="lactating", field=models.BooleanField(default=False),),
    ]
