<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-11-11 16:21
=======
# Generated by Django 3.0.5 on 2020-11-12 00:01
>>>>>>> origin/Dev-Maria

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("core", "0011_sheep_lactating"),
=======
        ('core', '0011_sheep_lactating'),
>>>>>>> origin/Dev-Maria
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Feed",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
=======
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
>>>>>>> origin/Dev-Maria
            ],
        ),
    ]
