# Generated by Django 3.0.5 on 2020-11-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('month', models.IntegerField()),
            ],
        ),
    ]
