# Generated by Django 3.0.5 on 2020-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="nickname",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
