# Generated by Django 3.0.5 on 2020-12-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shearing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shearing',
        ),
    ]
