# Generated by Django 3.1.7 on 2021-03-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_breed_nickname'),
        ('core', '0015_shearing'),
    ]

    operations = [
    ]
