# Generated by Django 3.1.6 on 2021-03-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shearing'),
        ('core', '0013_breed_nickname'),
    ]

    operations = [
    ]
