# Generated by Django 3.1.7 on 2021-03-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_shearing"),
        ("core", "0013_breed_nickname"),
    ]

    operations = []
