# Generated by Django 3.1.7 on 2021-03-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0016_merge_20210304_1814")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.CreateModel(
            name="Lots",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                (
                    "sheep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="lots", to="core.sheep"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="lots", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
