# Generated by Django 3.1.7 on 2021-03-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0017_auto_20210305_1810")]

    operations = [
        migrations.RemoveField(model_name="lots", name="sheep"),
        migrations.RemoveField(model_name="lots", name="user"),
    ]
