# Generated by Django 3.1.7 on 2021-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0018_auto_20210309_1655")]

    operations = [
        migrations.AlterField(model_name="lots", name="name", field=models.CharField(default=None, max_length=255))
    ]
