# Generated by Django 3.1.7 on 2021-03-09 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0019_auto_20210309_1713")]

    operations = [
        migrations.AddField(
            model_name="sheep",
            name="lots",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sheeps",
                to="core.lots",
            ),
        )
    ]
