# Generated by Django 3.1.7 on 2021-07-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sheep_lots'),
        ('core', '0016_merge_20210303_2355'),
    ]

    operations = [
    ]
